# Generated by Django 3.0.7 on 2020-06-22 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mileage', models.DecimalField(decimal_places=0, max_digits=4)),
                ('fuel', models.CharField(max_length=1)),
                ('emergency_lights', models.BooleanField()),
                ('driving_lights', models.BooleanField()),
                ('red_bag', models.BooleanField()),
                ('lp_fifteen', models.BooleanField()),
                ('trans_box', models.BooleanField()),
                ('bls_bag', models.BooleanField()),
                ('rtf_bags', models.BooleanField()),
                ('suction', models.BooleanField()),
                ('oxygen_bag', models.BooleanField()),
                ('signature', models.CharField(max_length=50)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle')),
            ],
        ),
    ]
