# Generated by Django 3.0.7 on 2020-06-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narcotics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narcotic',
            name='date',
            field=models.DateField(help_text='Please display in the form yyyy-mm-dd!'),
        ),
        migrations.AlterField(
            model_name='narcotic',
            name='incident_number',
            field=models.CharField(max_length=9, verbose_name='Incident #'),
        ),
        migrations.AlterField(
            model_name='narcotic',
            name='ketamine_in_stock_hundred_miligram_millileter',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Ketamine In Stock (in 100mg/ml)'),
        ),
        migrations.AlterField(
            model_name='narcotic',
            name='ketamine_in_stock_ten_miligram_millileter',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Ketamine In Stock (in 10mg/ml)'),
        ),
        migrations.AlterField(
            model_name='narcotic',
            name='medication_amount_mg',
            field=models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Medication Amount (in mg)'),
        ),
        migrations.AlterField(
            model_name='narcotic',
            name='medication_used',
            field=models.CharField(max_length=5, verbose_name='Medication Used'),
        ),
        migrations.AlterField(
            model_name='narcotic',
            name='morphine_in_stock',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Morphine In Stock'),
        ),
        migrations.AlterField(
            model_name='narcotic',
            name='provider_name',
            field=models.CharField(max_length=30, verbose_name='Provider Last Name'),
        ),
        migrations.AlterField(
            model_name='narcotic',
            name='seal_number',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Seal #'),
        ),
        migrations.AlterField(
            model_name='narcotic',
            name='shift_hours',
            field=models.DurationField(help_text='Please enter a time in the form hh:mm:ss indicating total duration!', verbose_name='Shift Hours'),
        ),
        migrations.AlterField(
            model_name='narcotic',
            name='versed_in_stock',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Versed In Stock'),
        ),
        migrations.AlterField(
            model_name='narcotic',
            name='waste_amount_mg',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Amount Wasted (in mg)'),
        ),
        migrations.AlterField(
            model_name='narcotic',
            name='waste_witness_initials',
            field=models.CharField(max_length=2, verbose_name='Waste Witness Initials'),
        ),
    ]
