# Generated by Django 3.0.7 on 2020-06-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('narcotics', '0002_auto_20200622_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narcotic',
            name='medication_used',
            field=models.CharField(max_length=10, verbose_name='Medication Used'),
        ),
    ]
