# Generated by Django 3.0.7 on 2020-06-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('oil', models.BooleanField()),
                ('transmission_fluid', models.BooleanField()),
                ('brake_fluid', models.BooleanField()),
                ('coolant_fluid', models.BooleanField()),
                ('lucas', models.BooleanField()),
                ('ems_equipment', models.BooleanField()),
                ('suction', models.BooleanField()),
                ('front_left_tire_pressure', models.DecimalField(decimal_places=0, max_digits=2)),
                ('front_right_tire_pressure', models.DecimalField(decimal_places=0, max_digits=2)),
                ('rear_left_tire_pressure', models.DecimalField(decimal_places=0, max_digits=2)),
                ('rear_right_tire_pressure', models.DecimalField(decimal_places=0, max_digits=2)),
                ('provider_name', models.CharField(max_length=30)),
                ('comments', models.TextField()),
            ],
        ),
    ]
