# Generated by Django 3.0.7 on 2020-06-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date',
            field=models.DateField(help_text='Please display as a date!'),
        ),
    ]
