# Generated by Django 3.0.7 on 2020-06-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20200622_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='lucas',
            field=models.BooleanField(verbose_name='LUCAS'),
        ),
    ]
