# Generated by Django 3.0.7 on 2020-06-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_auto_20200622_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date',
            field=models.DateField(help_text='Please display in the form <yyyy-mm:dd>!'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='front_left_tire_pressure',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Front Left Tire Pressure (in PSI)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='front_right_tire_pressure',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Front Right Tire Pressure (in PSI)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rear_left_tire_pressure',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Rear Left Tire Pressure (in PSI)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='rear_right_tire_pressure',
            field=models.DecimalField(decimal_places=0, max_digits=2, verbose_name='Rear Right Tire Pressure (in PSI)'),
        ),
    ]
