# Generated by Django 3.0.7 on 2020-06-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_auto_20200622_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date',
            field=models.DateField(help_text='Please display in the form yyyy-mm-dd!'),
        ),
    ]
